export type ClassroomExplanationSection = {
  title: string;
  body: string;
};

export type ClassroomExplanation = {
  questionId: string;
  sourceFile: string;
  tags: string[];
  title: string;
  subtitle: string;
  sections: ClassroomExplanationSection[];
  keyMessage: string;
};

// Generated by scripts/extract-classroom-explanations.mjs from the HTML files in html_questoes_23_arquivos.
// Duplicate source notes: dispneia.quest29.HRPP.2026: arquivo_05_asma_leve_gina_2025_primeira_versao.html -> arquivo_14_asma_leve_gina_2025_segunda_versao.html; dor-lombar.quest25.UERJ.2025: arquivo_19_lombalgia_inespecifica_75_90_melhoram.html -> dor-lombar.quest25.UERJ.2025.html.
export const classroomExplanationsByQuestionId: Record<string, ClassroomExplanation> = {
  "cefaleia.1": {
    "questionId": "cefaleia.1",
    "sourceFile": "arquivo_08_neuralgia_trigemeo_investigacao_rm.html",
    "tags": [
      "Neuralgia do trigêmeo",
      "Dor facial",
      "Diagnóstico etiológico",
      "Ressonância magnética"
    ],
    "title": "Neuralgia do trigêmeo: por que solicitar RM?",
    "subtitle": "Dor facial unilateral, em choque, paroxística e desencadeada por estímulos sugere neuralgia do trigêmeo e exige investigação etiológica adequada.",
    "sections": [
      {
        "title": "Ponto central",
        "body": "O quadro é típico de neuralgia do trigêmeo (CID-10: G50.0; diagnóstico clínico provável): dor facial unilateral, em choque, paroxística, intensa, desencadeada por estímulos como mastigação, frio ou toque, envolvendo ramos do nervo trigêmeo — neste caso, regiões maxilar e mandibular."
      },
      {
        "title": "Exame mais adequado",
        "body": "A investigação etiológica mais adequada é a ressonância magnética de crânio, preferencialmente com protocolo direcionado para o nervo trigêmeo."
      },
      {
        "title": "O que a RM pode avaliar",
        "body": "Ela permite avaliar compressão neurovascular, tumores, lesões estruturais e doenças desmielinizantes. A ICHD-3 descreve que a neuralgia trigeminal clássica pode ser confirmada por demonstração de compressão neurovascular na ressonância ou durante cirurgia; a European Academy of Neurology recomenda RM como parte da investigação. Fontes: ICHD-3, 2018; European Academy of Neurology, 2019."
      },
      {
        "title": "Por que os outros exames não são os melhores",
        "body": "A TC é inferior à RM para avaliar nervo trigêmeo, fossa posterior, compressão neurovascular, tumores pequenos e lesões desmielinizantes. EEG não é indicado para esclarecer dor facial típica de neuralgia trigeminal. Biópsia de artéria temporal é usada quando há suspeita de arterite de células gigantes (CID-10: M31.6; diagnóstico diferencial), o que não corresponde ao padrão descrito."
      }
    ],
    "keyMessage": "Resposta final: Ressonância magnética de crânio."
  },
  "cefaleia.15": {
    "questionId": "cefaleia.15",
    "sourceFile": "arquivo_10_hemicrania_paroxistica_indometacina.html",
    "tags": [
      "Cefaleia trigêmino-autonômica",
      "Crises curtas",
      "Alta frequência diária",
      "Indometacina"
    ],
    "title": "Hemicrania paroxística: crises curtas e resposta à indometacina.",
    "subtitle": "Crises unilaterais breves, muito frequentes e acompanhadas de sintomas autonômicos ipsilaterais favorecem hemicrania paroxística.",
    "sections": [
      {
        "title": "Ponto central",
        "body": "O quadro é mais compatível com hemicrania paroxística (CID-10: G44.0; diagnóstico clínico provável), uma cefaleia trigêmino-autonômica caracterizada por dor unilateral intensa, geralmente orbitária, supraorbitária ou temporal; crises curtas, de 2 a 30 minutos; alta frequência diária, geralmente mais de 5 crises por dia; sintomas autonômicos ipsilaterais, como lacrimejamento e hiperemia conjuntival."
      },
      {
        "title": "Por que hemicrania paroxística",
        "body": "O conjunto de crises curtas, alta frequência diária e sintomas autonômicos ipsilaterais favorece hemicrania paroxística."
      },
      {
        "title": "Tratamento característico",
        "body": "A característica-chave é a resposta absoluta à indometacina, que é o tratamento de escolha. Fonte: ICHD-3, 2018."
      },
      {
        "title": "Diferenças em relação aos diagnósticos alternativos",
        "body": "A cefaleia em salvas (CID-10: G44.0; diagnóstico diferencial) também causa dor unilateral com lacrimejamento e hiperemia ocular, e o verapamil é preventivo de escolha. Porém, as crises costumam durar 15 a 180 minutos. Tricíclicos não são tratamento preventivo padrão para cefaleia em salvas. Migrânea/enxaqueca (CID-10: G43.9; diagnóstico diferencial) costuma durar de 4 a 72 horas, frequentemente associada a náuseas, fotofobia ou fonofobia."
      }
    ],
    "keyMessage": "Resposta final: Hemicrania paroxística; indometacina."
  },
  "cefaleia.5": {
    "questionId": "cefaleia.5",
    "sourceFile": "arquivo_07_migranea_aura_tronco_cerebral.html",
    "tags": [
      "Migrânea",
      "Aura",
      "Tronco cerebral",
      "ICHD-3"
    ],
    "title": "Migrânea com aura do tronco cerebral.",
    "subtitle": "A ICHD-3 substituiu a antiga denominação migrânea basilar por migrânea com aura do tronco cerebral, caracterizada por sintomas reversíveis de tronco encefálico sem fraqueza motora.",
    "sections": [
      {
        "title": "Ponto central",
        "body": "A migrânea com aura do tronco cerebral (CID-10: G43.1; diagnóstico clínico conforme critérios) é a denominação usada pela ICHD-3 para o quadro antes chamado de migrânea basilar ou migrânea do tipo basilar. Fonte: ICHD-3, 2018."
      },
      {
        "title": "Como a aura pode se manifestar",
        "body": "A aura pode incluir sintomas reversíveis de tronco encefálico, como diplopia, zumbido, vertigem, disartria, hipoacusia, ataxia e redução do nível de consciência, sem fraqueza motora."
      },
      {
        "title": "Diferenças importantes",
        "body": "Na migrânea com aura, o tipo mais comum de aura é visual, não hemiparesia ou hemiplegia. Quando há fraqueza motora, trata-se de migrânea hemiplégica (CID-10: G43.1; diagnóstico clínico conforme critérios), forma específica e menos comum."
      },
      {
        "title": "Migrânea crônica",
        "body": "Na migrânea sem aura (CID-10: G43.0; diagnóstico clínico conforme critérios), a duração típica da cefaleia é de 4 a 72 horas. A migrânea crônica (CID-10: G43.7; diagnóstico clínico conforme critérios) exige cefaleia em 15 ou mais dias por mês por mais de 3 meses, com características de migrânea em pelo menos 8 dias por mês. Fontes: ICHD-3, 2018; Nature Reviews Neurology, 2021."
      }
    ],
    "keyMessage": "Resposta final: Migrânea com aura do tronco cerebral substitui o antigo conceito de migrânea basilar."
  },
  "cefaleia.quest28.FMUSP.2018": {
    "questionId": "cefaleia.quest28.FMUSP.2018",
    "sourceFile": "cefaleia.quest28.FMUSP.2018.html",
    "tags": [
      "Cefaleia em salvas",
      "Dor trigêmino-autonômica",
      "Tratamento agudo",
      "Profilaxia"
    ],
    "title": "Cefaleia em salvas: abortar a crise e prevenir recorrências.",
    "subtitle": "O reconhecimento da dor unilateral intensa, curta, recorrente e associada a sinais autonômicos ipsilaterais orienta a escolha do tratamento agudo e preventivo.",
    "sections": [
      {
        "title": "Ponto central da questão",
        "body": "O quadro é típico de cefaleia em salvas (CID-10: G44.0; diagnóstico clínico provável): dor unilateral muito intensa, em crises curtas e repetidas, associada a sinais autonômicos ipsilaterais, como hiperemia conjuntival e sudorese facial."
      },
      {
        "title": "Tratamento agudo adequado",
        "body": "Para o tratamento agudo, as principais opções são oxigênio a 100% em alto fluxo e triptanos, especialmente sumatriptano subcutâneo ou intranasal. Diretriz da European Academy of Neurology de 2023 recomenda oxigênio 100% ≥12 L/min e sumatriptano para crises agudas."
      },
      {
        "title": "Prevenção das crises",
        "body": "Para prevenção das crises, o fármaco de escolha é o verapamil. A associação correta é sumatriptano nasal para controle agudo e verapamil para tratamento crônico/preventivo."
      },
      {
        "title": "Armadilhas comuns",
        "body": "O oxigênio é adequado para controle agudo, mas gabapentina não é tratamento preventivo de primeira linha. Opioides não são indicados para crise de cefaleia em salvas; pregabalina não é profilaxia padrão. Dipirona tende a ser insuficiente; prednisona pode ser usada como terapia de transição em alguns casos, mas o preventivo de escolha é o verapamil."
      }
    ],
    "keyMessage": "Resposta final: Sumatriptano nasal + verapamil."
  },
  "cefaleia.quest42.SUS-BA.2023": {
    "questionId": "cefaleia.quest42.SUS-BA.2023",
    "sourceFile": "arquivo_12_nevralgia_trigemeo_diagnostico.html",
    "tags": [
      "Dor facial",
      "Nevralgia do trigêmeo",
      "Choque elétrico",
      "Gatilhos sensitivos"
    ],
    "title": "Nevralgia do trigêmeo: reconhecer o padrão da dor.",
    "subtitle": "Dor unilateral em choque, localizada nos ramos maxilar e mandibular e precipitada por mastigação ou frio, favorece nevralgia do trigêmeo.",
    "sections": [
      {
        "title": "Ponto central",
        "body": "O quadro é típico de nevralgia do trigêmeo (CID-10: G50.0; diagnóstico clínico provável). A dor costuma ser episódica, intensa e unilateral; em “choque elétrico”; desencadeada por estímulos leves, como mastigação, toque, escovação dentária, fala ou frio; localizada no território do nervo trigêmeo, especialmente nos ramos maxilar e mandibular."
      },
      {
        "title": "Território e gatilhos",
        "body": "Neste caso, a dor em hemiface esquerda, acometendo região maxilar e mandibular, com sensação de choque e gatilho por mastigação/frio, favorece fortemente esse diagnóstico. A ICHD-3 descreve neuralgia trigeminal como dor facial unilateral recorrente, em choques, desencadeada por estímulos inócuos. Fonte: ICHD-3, 2018."
      },
      {
        "title": "Por que não é nervo facial",
        "body": "O nervo facial é principalmente motor para a musculatura da mímica facial."
      },
      {
        "title": "Principais diferenciais",
        "body": "A cefaleia em salvas (CID-10: G44.0; diagnóstico diferencial) costuma causar dor orbitária, supraorbitária ou temporal, com sintomas autonômicos, não precipitada classicamente por mastigação ou frio em território maxilar/mandibular. Arterite de células gigantes (CID-10: M31.6; diagnóstico diferencial) costuma ter cefaleia temporal nova, dor à palpação da artéria temporal, claudicação mandibular, sintomas sistêmicos e risco de perda visual."
      }
    ],
    "keyMessage": "Resposta final: Nevralgia do nervo trigêmeo."
  },
  "dispneia.quest13.SCMSP.2024": {
    "questionId": "dispneia.quest13.SCMSP.2024",
    "sourceFile": "arquivo_13_legionelose_pneumonia_atipica.html",
    "tags": [
      "Legionelose",
      "Pneumonia atípica",
      "Hiponatremia",
      "Bradicardia relativa"
    ],
    "title": "Legionelose: quando a pneumonia vem com sinais sistêmicos.",
    "subtitle": "A doença dos legionários é uma pneumonia atípica que pode cursar com sintomas gastrointestinais, hiponatremia e dissociação pulso-temperatura.",
    "sections": [
      {
        "title": "Ponto central",
        "body": "A legionelose, especialmente a doença dos legionários (CID-10: A48.1; diagnóstico clínico-laboratorial provável/confirmado conforme testes), é uma pneumonia atípica causada principalmente por Legionella pneumophila."
      },
      {
        "title": "Achados clássicos",
        "body": "A pneumonia por Legionella pode cursar com dor, febre e pneumonia; sintomas gastrointestinais, como diarreia, náuseas e vômitos; hiponatremia; dissociação pulso-temperatura, também chamada de bradicardia relativa."
      },
      {
        "title": "Hiponatremia e SIADH",
        "body": "A hiponatremia é classicamente associada à doença dos legionários, embora a explicação exclusiva por SIADH seja discutida. Estudos mostram associação frequente com hiponatremia, mas nem sempre com aumento de ADH. Fontes: CDC, 2024; StatPearls/NCBI Bookshelf, 2025; Schuetz et al., 2013."
      },
      {
        "title": "Armadilhas comuns",
        "body": "A doença não ocorre apenas em imunocomprometidos. Idade avançada, tabagismo, doença pulmonar crônica e imunossupressão aumentam o risco, mas pessoas imunocompetentes também podem adoecer. O tratamento de escolha não é vancomicina com meropenem; opções usuais incluem azitromicina ou levofloxacino. Sintomas extrapulmonares podem ocorrer, especialmente gastrointestinais e neurológicos."
      }
    ],
    "keyMessage": "Resposta final: Pneumonia por Legionella pode cursar com sintomas gastrointestinais, hiponatremia e dissociação pulso-temperatura."
  },
  "dispneia.quest16.FAMEMA.2024": {
    "questionId": "dispneia.quest16.FAMEMA.2024",
    "sourceFile": "dispneia.quest16.FAMEMA.2024.html",
    "tags": [
      "IAM com supra",
      "Disfunção ventricular esquerda",
      "Mortalidade pós-IAM",
      "Conduta antes da alta"
    ],
    "title": "Eplerenona no pós-IAM com FEVE reduzida",
    "subtitle": "Quando o IAM com supra evolui com disfunção sistólica e sinais de insuficiência cardíaca, a escolha terapêutica antes da alta deve priorizar intervenção com impacto em mortalidade.",
    "sections": [
      {
        "title": "Ponto central da questão",
        "body": "O paciente teve IAM com supra anterior (CID-10: I21.0), foi reperfundido, mas permaneceu com disfunção sistólica ventricular esquerda importante, com FEVE de 34%, além de sinais de insuficiência cardíaca pós-infarto (CID-10: I50.2; diagnóstico sindrômico/provisório), como estertores bibasilares e disfunção ventricular no ecocardiograma."
      },
      {
        "title": "Conduta que reduz mortalidade",
        "body": "Nessa situação, há indicação de adicionar um antagonista do receptor mineralocorticoide, como eplerenona, desde que não haja contraindicações, como hipercalemia ou insuficiência renal importante. O estudo EPHESUS demonstrou redução de mortalidade em pacientes pós-IAM com disfunção ventricular esquerda e insuficiência cardíaca tratados com eplerenona. Diretrizes atuais de síndrome coronariana aguda também mantêm essa recomendação em pacientes com FEVE reduzida após IAM."
      },
      {
        "title": "Por que não amiodarona ou CDI agora",
        "body": "A amiodarona não reduz mortalidade como prevenção primária após IAM apenas por FEVE baixa. Ela é usada em arritmias específicas, como taquiarritmias ventriculares sustentadas ou fibrilação atrial selecionada, o que não foi descrito no caso. O CDI pode reduzir mortalidade em pacientes com FEVE persistentemente reduzida, mas não deve ser implantado imediatamente antes da alta após IAM recente para prevenção primária. Em geral, reavalia-se a FEVE após período de tratamento otimizado, usualmente pelo menos 40 dias após o IAM."
      },
      {
        "title": "Por que não trocar o IECA por sacubitril/valsartana",
        "body": "Sacubitril/valsartana é importante na insuficiência cardíaca crônica com fração de ejeção reduzida, mas no contexto imediato pós-IAM, a evidência de redução adicional de mortalidade sobre IECA/ARB não é superior à da eplerenona para este cenário. O paciente já está em IECA, que é apropriado no pós-IAM com FEVE reduzida."
      }
    ],
    "keyMessage": "Resposta final: Adicionar eplerenona."
  },
  "dispneia.quest29.HRPP.2026": {
    "questionId": "dispneia.quest29.HRPP.2026",
    "sourceFile": "arquivo_14_asma_leve_gina_2025_segunda_versao.html",
    "tags": [
      "Asma leve",
      "GINA 2025",
      "Broncoprovocação positiva",
      "ICS-formoterol"
    ],
    "title": "Asma leve: tratar mesmo com sintomas infrequentes.",
    "subtitle": "Sintomas respiratórios variáveis associados a broncoprovocação positiva confirmam asma e indicam tratamento contendo corticoide inalatório.",
    "sections": [
      {
        "title": "Ponto central",
        "body": "O paciente tem asma (CID-10: J45.9; diagnóstico confirmado), pois apresenta sintomas respiratórios variáveis — tosse e sibilância desencadeadas por poeira — e teste de broncoprovocação positivo, compatível com hiperresponsividade brônquica."
      },
      {
        "title": "Por que iniciar tratamento",
        "body": "Segundo o GINA 2025, adultos e adolescentes com asma devem receber tratamento contendo corticoide inalatório, mesmo quando os sintomas são infrequentes."
      },
      {
        "title": "Tratamento preferencial",
        "body": "A opção preferencial, quando disponível, é baixa dose de corticoide inalatório + formoterol conforme necessidade, isto é, usado apenas quando houver sintomas nas etapas iniciais."
      },
      {
        "title": "Alternativa, não preferência",
        "body": "Há conclusão diagnóstica: sintomas típicos e broncoprovocação positiva confirmam asma. Reduzir exposição à poeira é importante, mas não substitui o tratamento farmacológico. Corticoide inalatório diário em baixa dose + SABA de resgate é alternativa possível, mas não é a estratégia preferencial quando ICS-formoterol está disponível."
      }
    ],
    "keyMessage": "Resposta final: Corticoide inalatório + formoterol em caso de sintomas."
  },
  "dispneia.quest40.UNESP.2026": {
    "questionId": "dispneia.quest40.UNESP.2026",
    "sourceFile": "dispneia.quest40.UNESP.2026.html",
    "tags": [
      "Asma pediátrica",
      "Escolares",
      "SMART/MART",
      "Corticoide inalatório"
    ],
    "title": "Asma em escolares: manutenção e resgate com o mesmo inalador.",
    "subtitle": "Em crianças de 6 a 11 anos, o tratamento deve conter corticosteroide inalatório, e a combinação budesonida + formoterol pode ser usada em estratégia de manutenção e alívio.",
    "sections": [
      {
        "title": "Ponto central da questão",
        "body": "A alternativa correta é a D, pois a associação budesonida + formoterol pode ser usada como tratamento de manutenção e alívio em crianças de 6 a 11 anos com asma (CID-10: J45.9; diagnóstico clínico conforme contexto), em esquema conhecido como SMART/MART."
      },
      {
        "title": "Estratégia SMART/MART",
        "body": "Nesse modelo, o mesmo inalador é usado diariamente para controle e também em doses adicionais para alívio dos sintomas. O GINA 2024 recomenda que crianças de 6 a 11 anos não sejam tratadas apenas com SABA e que recebam tratamento contendo corticosteroide inalatório."
      },
      {
        "title": "Por que o formoterol importa",
        "body": "Para etapas 3–4, uma das opções é o uso de ICS-formoterol como manutenção e resgate, sendo o formoterol o LABA adequado para essa estratégia por ter início rápido de ação."
      },
      {
        "title": "Armadilhas comuns",
        "body": "O PCDT da Asma do Ministério da Saúde, de 2021, contempla broncodilatadores de curta ação, como salbutamol e fenoterol. Porém, as diretrizes atuais enfatizam que crianças não devem ser manejadas apenas com SABA; o tratamento deve incluir corticosteroide inalatório. A associação central para SMART/MART é budesonida + formoterol, não budesonida + salbutamol. Cursos repetidos de corticosteroide sistêmico aumentam risco de eventos adversos."
      }
    ],
    "keyMessage": "Resposta final: Budesonida + formoterol em estratégia SMART/MART."
  },
  "disuria.quest09.UnP.2026": {
    "questionId": "disuria.quest09.UnP.2026",
    "sourceFile": "arquivo_16_calculo_renal_assintomatico_12mm.html",
    "tags": [
      "Nefrolitíase",
      "Cálculo renal",
      "Maior que 10 mm",
      "Tratamento ativo"
    ],
    "title": "Cálculo renal de 12 mm: por que intervir?",
    "subtitle": "Mesmo sem sintomas, cálculos renais maiores que 10 mm têm menor chance de eliminação espontânea e maior risco de complicações futuras.",
    "sections": [
      {
        "title": "Ponto central",
        "body": "O paciente tem nefrolitíase renal (CID-10: N20.0; diagnóstico por imagem), com cálculo de 12 mm."
      },
      {
        "title": "Por que o tamanho importa",
        "body": "Cálculos renais assintomáticos pequenos podem ser apenas acompanhados, especialmente quando menores que 10 mm, não obstrutivos e sem crescimento. Porém, cálculos maiores que 10 mm têm menor chance de eliminação espontânea e maior risco de crescimento, dor, obstrução ou infecção."
      },
      {
        "title": "Riscos de não tratar",
        "body": "Ser assintomático não significa ausência de risco. Observação anual é mais adequada para cálculos pequenos. Citrato de potássio pode ser indicado em casos específicos, mas não é tratamento exclusivo adequado para cálculo renal de 12 mm sem avaliação metabólica/composicional."
      },
      {
        "title": "Conduta indicada",
        "body": "A melhor conduta é intervenção ativa, como litotripsia extracorpórea ou procedimento endourológico, individualizando conforme localização, densidade, anatomia renal e preferência do paciente. Diretrizes da European Association of Urology indicam tratamento ativo para cálculos renais de 10–20 mm com litotripsia, ureteroscopia flexível ou nefrolitotripsia percutânea, conforme o caso. Fonte: EAU Guidelines on Urolithiasis, 2025."
      }
    ],
    "keyMessage": "Resposta final: Litotripsia extracorpórea ou procedimento endourológico devido ao tamanho."
  },
  "disuria.quest20.HOS-SP.2021": {
    "questionId": "disuria.quest20.HOS-SP.2021",
    "sourceFile": "arquivo_17_pielonefrite_aguda_gestacao.html",
    "tags": [
      "Gestação",
      "Pielonefrite aguda",
      "Antibiótico parenteral",
      "Ceftriaxona"
    ],
    "title": "Pielonefrite na gestação: iniciar tratamento parenteral.",
    "subtitle": "Dor em flanco associada a sintomas urinários e urina tipo I infecciosa sugere pielonefrite, condição que na gestação exige abordagem inicial mais rigorosa.",
    "sections": [
      {
        "title": "Ponto central",
        "body": "O quadro sugere pielonefrite aguda na gestação (CID-10: O23.0; diagnóstico clínico provável), pois há sintomas urinários baixos associados a dor em flanco, além de urina tipo I compatível com infecção."
      },
      {
        "title": "Por que é manejo hospitalar",
        "body": "Na gestação, pielonefrite deve ser tratada inicialmente com antibiótico parenteral, geralmente em ambiente hospitalar, devido ao risco de sepse, anemia, insuficiência respiratória e parto prematuro."
      },
      {
        "title": "Antibiótico inicial adequado",
        "body": "A ceftriaxona é uma opção adequada de tratamento inicial. A FEBRASGO recomenda, para infecção urinária alta na gestação, antibiótico endovenoso por pelo menos 2–3 dias, incluindo ceftriaxona 1 g 12/12h ou 2 g 24/24h. O ACOG também recomenda manejo inicial hospitalar com antibiótico parenteral de boa penetração renal. Fontes: FEBRASGO, 2021; ACOG, 2023."
      },
      {
        "title": "Por que as outras opções não são as melhores",
        "body": "Fluoroquinolonas não são primeira escolha na gestação. Aminoglicosídeo pode ter uso em situações específicas, mas não é a melhor opção inicial entre as alternativas. Nitrofurantoína pode ser usada para cistite baixa, mas não é adequada para pielonefrite, pois não atinge níveis terapêuticos suficientes no parênquima renal."
      }
    ],
    "keyMessage": "Resposta final: Ceftriaxona."
  },
  "disuria.quest20.UnP.2026": {
    "questionId": "disuria.quest20.UnP.2026",
    "sourceFile": "arquivo_23_cistite_recorrente_pos_coital.html",
    "tags": [
      "Cistite recorrente",
      "Pós-coital",
      "Profilaxia",
      "Menor uso de antibiótico"
    ],
    "title": "Cistite recorrente pós-coital: prevenir com estratégia direcionada.",
    "subtitle": "Quando os episódios de cistite ocorrem de forma temporalmente associada à relação sexual, a profilaxia pós-coital reduz exposição antibiótica em comparação à profilaxia contínua.",
    "sections": [
      {
        "title": "Ponto central",
        "body": "O quadro é compatível com cistite recorrente não complicada (CID-10: N30.0; diagnóstico clínico-laboratorial provável), pois houve múltiplos episódios sintomáticos confirmados por cultura."
      },
      {
        "title": "Relação temporal com o coito",
        "body": "Como os episódios são claramente relacionados à relação sexual, a melhor estratégia é profilaxia pós-coital com dose única de antibiótico. Dose única após relação sexual é a melhor opção quando as cistites ocorrem nas 24–48 horas após o coito."
      },
      {
        "title": "Melhor medida profilática",
        "body": "Essa abordagem é eficaz e expõe a paciente a menor quantidade total de antibiótico do que a profilaxia diária contínua, reduzindo eventos adversos e pressão seletiva para resistência. Diretrizes da EAU recomendam profilaxia antimicrobiana contínua ou pós-coital quando medidas não antimicrobianas falham, e a profilaxia pós-coital é especialmente adequada quando as infecções são temporalmente associadas ao ato sexual."
      },
      {
        "title": "Por que as outras opções não são as melhores",
        "body": "Antibioticoprofilaxia contínua diária por 6 meses é eficaz, mas costuma ser reservada para casos sem relação clara com relação sexual ou quando outras estratégias falham. Cranberry pode ter benefício modesto e evidência variável, mas não é a medida mais eficaz para cistite recorrente claramente pós-coital. Lavagem perineal com antisséptico não é recomendada como profilaxia eficaz e pode causar irritação local e alteração da microbiota."
      }
    ],
    "keyMessage": "Resposta final: Dose única de antibiótico após relação sexual."
  },
  "disuria.quest21.SCM-SP.2025": {
    "questionId": "disuria.quest21.SCM-SP.2025",
    "sourceFile": "arquivo_15_bacteriuria_assintomatica_gestacao.html",
    "tags": [
      "Pré-natal",
      "Bacteriúria assintomática",
      "Urocultura positiva",
      "Tratamento na gestação"
    ],
    "title": "Bacteriúria assintomática na gestação: tratar é a conduta.",
    "subtitle": "Na gestante, urocultura com E. coli ≥100.000 UFC/mL indica bacteriúria significativa e exige tratamento, mesmo sem sintomas urinários.",
    "sections": [
      {
        "title": "Ponto central",
        "body": "A paciente apresenta bacteriúria assintomática na gestação (CID-10: O23.4; diagnóstico laboratorial confirmado), definida por urocultura com crescimento bacteriano significativo, geralmente ≥ 100.000 UFC/mL, mesmo sem sintomas urinários."
      },
      {
        "title": "Por que tratar",
        "body": "Na gestação, a bacteriúria assintomática deve ser tratada, pois aumenta o risco de pielonefrite (CID-10: N10; complicação possível), parto prematuro e baixo peso ao nascer. O ACOG recomenda tratar bacteriúria assintomática na gestação com antibiótico direcionado por 5 a 7 dias quando a urocultura mostra ≥100.000 UFC/mL. Fonte: ACOG Clinical Consensus, 2023."
      },
      {
        "title": "Conduta adequada",
        "body": "A amoxicilina-clavulanato por 7 dias é uma opção possível para tratamento de bacteriúria assintomática por E. coli na gestação, idealmente guiada por antibiograma."
      },
      {
        "title": "Armadilhas comuns",
        "body": "Trimetoprima/sulfametoxazol não é a melhor opção na gestação inicial, especialmente no primeiro trimestre, e 3 dias é duração curta. E. coli ≥100.000 UFC/mL não deve ser presumida como contaminação. Na gestação, bacteriúria assintomática não deve ser apenas observada."
      }
    ],
    "keyMessage": "Resposta final: Prescrever amoxicilina-ácido clavulânico por 7 dias."
  },
  "disuria.quest23.UnP.2026": {
    "questionId": "disuria.quest23.UnP.2026",
    "sourceFile": "arquivo_09_uretrite_nao_gonococica_chlamydia.html",
    "tags": [
      "Uretrite",
      "IST",
      "Corrimento uretral",
      "Chlamydia trachomatis"
    ],
    "title": "Uretrite não gonocócica: quadro arrastado e corrimento discreto.",
    "subtitle": "Corrimento uretral mucoide discreto, prurido e sintomas menos exuberantes após relação desprotegida sugerem uretrite não gonocócica.",
    "sections": [
      {
        "title": "Ponto central",
        "body": "O quadro é compatível com uretrite não gonocócica (CID-10: N34.1; diagnóstico clínico provável). A apresentação típica é mais arrastada, com corrimento mucoide ou mucopurulento discreto, prurido uretral e sintomas menos exuberantes que na gonorreia."
      },
      {
        "title": "Agente mais provável",
        "body": "O principal agente de uretrite não gonocócica é a Chlamydia trachomatis. O CDC descreve C. trachomatis como responsável por 15% a 40% dos casos de uretrite não gonocócica, variando conforme idade e população. O PCDT-IST do Ministério da Saúde também destaca clamídia e gonococo como causas centrais na síndrome do corrimento uretral."
      },
      {
        "title": "Por que não gonococo exclusivo",
        "body": "A uretrite gonocócica (CID-10: A54.0; diagnóstico diferencial) costuma causar corrimento mais abundante e purulento, com disúria mais marcada."
      },
      {
        "title": "Outros diferenciais",
        "body": "Trichomonas vaginalis pode causar uretrite em homens, mas é menos provável nesse padrão clínico. Herpes genital (CID-10: A60.0; diagnóstico diferencial) costuma cursar com vesículas, úlceras dolorosas, disúria e dor local."
      }
    ],
    "keyMessage": "Resposta final: Chlamydia trachomatis."
  },
  "disuria.quest29.UnP.2026": {
    "questionId": "disuria.quest29.UnP.2026",
    "sourceFile": "arquivo_11_calculo_renal_13mm_polo_inferior.html",
    "tags": [
      "Nefrolitíase",
      "Cálculo renal",
      "Polo inferior",
      "Tratamento ativo"
    ],
    "title": "Cálculo renal de 13 mm: quando observar não basta.",
    "subtitle": "Mesmo assintomático, um cálculo renal de 13 mm em polo inferior tem baixa chance de resolução espontânea e pode justificar intervenção ativa.",
    "sections": [
      {
        "title": "Ponto central",
        "body": "O paciente tem nefrolitíase renal esquerda (CID-10: N20.0; diagnóstico por imagem), com cálculo de 13 mm em polo inferior."
      },
      {
        "title": "Por que o tamanho muda a conduta",
        "body": "Apesar de estar assintomático, o tamanho do cálculo é relevante. Cálculos renais assintomáticos pequenos podem ser apenas acompanhados, mas cálculos entre 10 e 20 mm, especialmente em polo inferior, frequentemente têm indicação de tratamento ativo, considerando baixa chance de eliminação espontânea e risco futuro de crescimento, obstrução, dor ou infecção."
      },
      {
        "title": "Opções de tratamento ativo",
        "body": "As diretrizes da European Association of Urology de 2025 indicam que, para cálculos renais de 10 a 20 mm, as opções terapêuticas incluem litotripsia extracorpórea, ureteroscopia flexível ou nefrolitotripsia percutânea, dependendo de localização, composição, anatomia e fatores do paciente. Para polo inferior, a ureteroscopia flexível costuma ter melhor taxa livre de cálculo que a litotripsia em muitos cenários."
      },
      {
        "title": "Por que não apenas observar ou tratar clinicamente",
        "body": "Observação é mais adequada para cálculos pequenos, geralmente menores que 10 mm. Citrato de potássio pode ser útil em situações específicas, mas não é tratamento exclusivo adequado para cálculo renal de 13 mm sem definição metabólica/composicional. Ser assintomático não significa ausência de risco."
      }
    ],
    "keyMessage": "Resposta final: Intervenção ativa — litotripsia extracorpórea ou ureteroscopia — devido ao tamanho."
  },
  "dor-lombar.quest19.REVALIDA.2025": {
    "questionId": "dor-lombar.quest19.REVALIDA.2025",
    "sourceFile": "arquivo_18_lombalgia_mecanica_sem_imagem_inicial.html",
    "tags": [
      "Lombalgia mecânica",
      "Sem sinais de alerta",
      "Evitar imagem",
      "Manter-se ativo"
    ],
    "title": "Lombalgia sem sinais de alerta: tratar sem imagem inicial.",
    "subtitle": "Na lombalgia mecânica inespecífica, sem déficit neurológico ou sinais sistêmicos, a conduta inicial prioriza atividade, exercício e controle sintomático.",
    "sections": [
      {
        "title": "Ponto central",
        "body": "O quadro é compatível com lombalgia mecânica/subaguda inespecífica (CID-10: M54.5; diagnóstico clínico provável), relacionada a esforço físico, sem sinais de alerta e sem déficit neurológico."
      },
      {
        "title": "Por que não solicitar imagem",
        "body": "Diretrizes internacionais recomendam evitar exames de imagem em lombalgia sem sinais de alerta, pois achados degenerativos são comuns mesmo em pessoas assintomáticas e podem levar a intervenções desnecessárias. Fontes: American College of Physicians, 2017; NICE Guideline NG59, 2020."
      },
      {
        "title": "Conduta recomendada",
        "body": "Nesse cenário, a conduta adequada é não solicitar exames de imagem inicialmente, orientar manutenção das atividades habituais conforme tolerância, prática de exercícios e medidas analgésicas. Anti-inflamatórios não esteroides podem ser usados por curto período, e relaxantes musculares podem ser considerados quando há espasmo ou dor muscular importante."
      },
      {
        "title": "Armadilhas comuns",
        "body": "A irradiação para membro inferior, isoladamente, não indica ressonância. Radiografia também não é indicada na ausência de sinais de alerta. Corticoide sistêmico não é tratamento de rotina. Repouso prolongado piora a recuperação funcional."
      }
    ],
    "keyMessage": "Resposta final: Não solicitar exames complementares; orientar exercício físico; prescrever anti-inflamatório não esteroide associado a relaxante muscular."
  },
  "dor-lombar.quest25.UERJ.2025": {
    "questionId": "dor-lombar.quest25.UERJ.2025",
    "sourceFile": "dor-lombar.quest25.UERJ.2025.html",
    "tags": [
      "Lombalgia",
      "Atenção primária",
      "Imagem criteriosa",
      "Evolução natural"
    ],
    "title": "Lombalgia: quando a imagem não é o ponto central.",
    "subtitle": "A maioria dos quadros de lombalgia inespecífica evolui favoravelmente, e exames de imagem devem ser reservados para situações com sinais de alerta.",
    "sections": [
      {
        "title": "Ponto central da questão",
        "body": "A maioria dos casos de lombalgia inespecífica (CID-10: M54.5; diagnóstico clínico provável) tem evolução favorável, com melhora espontânea ou com tratamento conservador em semanas a poucos meses."
      },
      {
        "title": "Evolução esperada",
        "body": "Diretrizes e revisões indicam que a maior parte dos quadros melhora dentro de até 6 a 12 semanas, embora recorrências sejam comuns. Cerca de 75-90% dos casos melhoram em até três meses."
      },
      {
        "title": "Uso criterioso de imagem",
        "body": "Não é essencial realizar exame de imagem em toda lombalgia. Radiografia, tomografia ou ressonância ficam reservadas para casos com sinais de alerta, como suspeita de fratura, câncer, infecção, síndrome da cauda equina ou déficit neurológico progressivo."
      },
      {
        "title": "Armadilhas comuns",
        "body": "A ciatalgia (CID-10: M54.3; diagnóstico clínico sindrômico) pode decorrer de dor radicular, mas nem toda dor irradiada para membro inferior corresponde a radiculopatia verdadeira. É comum encontrar alterações em exames de imagem de pessoas assintomáticas, como protrusões discais, degeneração discal e artrose facetária."
      }
    ],
    "keyMessage": "Resposta final: A maioria dos casos melhora em até três meses."
  },
  "dor-lombar.quest26.AMRIGS.2017": {
    "questionId": "dor-lombar.quest26.AMRIGS.2017",
    "sourceFile": "arquivo_22_lombalgia_aps_indicacao_clinica_nao_administrativa.html",
    "tags": [
      "Lombalgia",
      "Atenção Primária",
      "Sinais de alerta",
      "Exames complementares"
    ],
    "title": "Lombalgia: indicação clínica, não administrativa.",
    "subtitle": "Na abordagem da lombalgia, exames e avaliação cirúrgica devem ser guiados por sinais de alerta e gravidade, não apenas por demandas documentais.",
    "sections": [
      {
        "title": "Ponto central",
        "body": "Na lombalgia (CID-10: M54.5; diagnóstico clínico sindrômico), exames complementares ou avaliação cirúrgica devem ser considerados quando há sinais de alerta, como dor noturna persistente, piora progressiva, refratariedade ao tratamento, déficit motor ou sensitivo, suspeita de infecção, câncer, fratura ou síndrome da cauda equina."
      },
      {
        "title": "Sinais que justificam investigação",
        "body": "Dor noturna persistente pode ser sinal de alerta, especialmente se associada a perda de peso, febre, história de câncer ou piora progressiva. Dor que não melhora com tratamento adequado ou que progride pode justificar investigação."
      },
      {
        "title": "Déficits neurológicos",
        "body": "Déficits neurológicos podem sugerir radiculopatia significativa, compressão neural ou síndrome da cauda equina."
      },
      {
        "title": "O que não é indicação clínica",
        "body": "A necessidade de emitir laudo para o INSS, por si só, não é indicação clínica de exame de imagem nem de avaliação cirúrgica. A indicação deve ser baseada no quadro clínico e nos sinais de gravidade, não em demanda administrativa. Fontes: NICE Guideline NG59, 2020; American College of Physicians, 2017. Emissão de laudo para o INSS é demanda documental/administrativa."
      }
    ],
    "keyMessage": "Resposta final: Emissão de laudo para o INSS não indica, isoladamente, exame complementar ou avaliação cirúrgica."
  },
  "dor-lombar.quest31.FMUSP.2026": {
    "questionId": "dor-lombar.quest31.FMUSP.2026",
    "sourceFile": "arquivo_06_lombalgia_aguda_risco_cronificacao.html",
    "tags": [
      "Lombalgia aguda",
      "Cronificação",
      "Incapacidade funcional",
      "Prognóstico"
    ],
    "title": "Lombalgia aguda: quando a dor intensa sinaliza maior risco.",
    "subtitle": "No início do episódio, a intensidade da dor e o impacto funcional são dados clínicos importantes para estimar risco de evolução para dor persistente.",
    "sections": [
      {
        "title": "Ponto central da questão",
        "body": "A paciente apresenta lombalgia aguda com irradiação para membro inferior direito (CID-10: M54.4; diagnóstico clínico provável), sem déficit motor ou sensitivo."
      },
      {
        "title": "Fator de risco mais importante",
        "body": "O principal fator de risco para cronificação descrito na questão é a dor intensa associada à incapacidade funcional."
      },
      {
        "title": "Por que isso prediz cronificação",
        "body": "Quanto maior a intensidade da dor e maior o impacto funcional no início do episódio, maior o risco de evolução para dor persistente. Revisão sistemática de 2021 identificou maior intensidade da dor e limitação funcional como fatores prognósticos frequentes para cronificação da lombalgia."
      },
      {
        "title": "Fatores associados, mas menos específicos",
        "body": "Obesidade pode estar associada à lombalgia, mas isoladamente é menos específica. Tabagismo se associa a maior risco de lombalgia e recorrência, mas não é o melhor preditor clínico para cronificação imediata. Distúrbios do sono podem piorar dor crônica e funcionalidade, mas uso de benzodiazepínico não é o fator clássico principal."
      }
    ],
    "keyMessage": "Resposta final: Dor intensa gerando incapacidade funcional."
  },
  "dor-lombar.quest32.AMP.2024": {
    "questionId": "dor-lombar.quest32.AMP.2024",
    "sourceFile": "arquivo_20_lombalgia_aps_bandeiras_amarelas.html",
    "tags": [
      "Lombalgia aguda",
      "Atenção Primária",
      "Bandeiras amarelas",
      "Cronificação"
    ],
    "title": "Lombalgia na APS: olhar além da dor.",
    "subtitle": "Na lombalgia aguda inespecífica, a avaliação deve incluir sinais de alerta graves e fatores psicossociais que aumentam o risco de incapacidade e cronificação.",
    "sections": [
      {
        "title": "Ponto central",
        "body": "A paciente apresenta quadro compatível com lombalgia aguda inespecífica (CID-10: M54.5; diagnóstico clínico provável), relacionada a esforço físico, sem sinais de gravidade descritos."
      },
      {
        "title": "Bandeiras amarelas",
        "body": "Na abordagem da lombalgia na Atenção Primária, além de avaliar sinais de alerta graves — bandeiras vermelhas —, também é importante identificar bandeiras amarelas, que são fatores psicossociais associados a maior risco de incapacidade, recorrência e cronificação da dor. Entre elas estão medo excessivo de movimento, catastrofização, humor deprimido, pessimismo, insatisfação no trabalho e crenças negativas sobre a dor. Fontes: NICE Guideline NG59, 2020; American College of Physicians, 2017."
      },
      {
        "title": "O que não deve ser confundido",
        "body": "Dor irradiada até a região glútea não confirma radiculopatia. Repouso absoluto não é recomendado; a orientação é manter-se ativo dentro do tolerável."
      },
      {
        "title": "Condutas e avaliação inicial",
        "body": "Mesmo em lombalgia aguda, é essencial investigar sinais de alerta, como febre, história de câncer, trauma, perda de peso, uso crônico de corticosteroides, imunossupressão, déficit neurológico progressivo e sintomas de síndrome da cauda equina."
      }
    ],
    "keyMessage": "Resposta final: Ideias catastróficas, depressão e pessimismo são bandeiras amarelas e devem ser abordadas."
  },
  "dor-lombar.quest35.UFPR.2021": {
    "questionId": "dor-lombar.quest35.UFPR.2021",
    "sourceFile": "arquivo_21_dor_costas_historia_ocupacional_recreacional.html",
    "tags": [
      "Dor nas costas",
      "Atenção Primária",
      "História clínica",
      "Fatores funcionais"
    ],
    "title": "Dor nas costas: investigar rotina, trabalho e atividade física.",
    "subtitle": "Na avaliação da lombalgia, compreender ocupação, lazer, limitações e barreiras funcionais ajuda a construir um plano terapêutico mais adequado.",
    "sections": [
      {
        "title": "Ponto central",
        "body": "Na avaliação de dor nas costas/lombalgia (CID-10: M54.5; diagnóstico clínico sindrômico provável), a história ocupacional e recreacional é importante porque ajuda a identificar sobrecarga mecânica, posturas mantidas, movimentos repetitivos, sedentarismo, atividades físicas inadequadas e barreiras para reabilitação."
      },
      {
        "title": "Por que a rotina importa",
        "body": "Essas informações ajudam a orientar diagnóstico, tratamento, adaptação de atividade física, perda ponderal e medidas funcionais. Fontes: NICE Guideline NG59, 2020; American College of Physicians, 2017."
      },
      {
        "title": "Aplicando ao caso",
        "body": "No caso, Rogério tem obesidade, dor mecânica, limitação por artrose do joelho e realiza caminhadas e pedaladas com dificuldade. Essas informações ajudam a orientar tratamento, adaptação de atividade física, perda ponderal e medidas funcionais."
      },
      {
        "title": "Armadilhas comuns",
        "body": "Trauma recente e febre são sinais de alerta vermelhos. Fatores psicossociais, como medo, catastrofização, depressão e insatisfação laboral, são bandeiras amarelas. O exame físico continua essencial. Exames de imagem não substituem avaliação clínica e não devem ser solicitados rotineiramente na ausência de sinais de alerta. A maioria dos casos é manejada na Atenção Primária."
      }
    ],
    "keyMessage": "Resposta final: A história ocupacional e recreacional pode fornecer informações valiosas para o diagnóstico e tratamento."
  }
};
